---
- hosts: master_nodes
  become: true
  roles:
    - role: elastic.elasticsearch
  vars:
    es_version: 7.3.2
    es_data_dirs:
      - "/opt/elasticsearch/data"
    es_log_dir: "/opt/elasticsearch/logs"
    es_config:
      cluster.name: "vagrant-elk-demo"
      node.name: "{{ inventory_hostname }}"
      network.host: "{{ ansible_eth1.ipv4.address }}"
      http.port: 9200
      cluster.initial_master_nodes: "{{ groups['master_nodes'] | list }}"
      discovery.seed_hosts: "{{ groups['master_nodes'] | map('extract', hostvars, ['ansible_eth1', 'ipv4', 'address']) | list }}"
      transport.port: 9300
      node.master: true
      node.voting_only: false 
      node.data: false
      node.ingest: false
      node.ml: false
      xpack.ml.enabled: true
      cluster.remote.connect: false
      bootstrap.memory_lock: false
    es_heap_size: 512m
    es_api_host: "{{ ansible_eth1.ipv4.address }}"
